export const HOST_URL = "https://www.anapioficeandfire.com/api"

export const ENDPOINT = {
    CHARACTERS: "/characters"
}

export const TOGGLE_INIT = {
    alive: { title: "생존인물만", active: false },
    female: { title: "여자", active: false },
    noTvSeries: { title: "tvSeries 없음", active: false },
    reset: { title: "초기화", active: false }
}

export const TEST_DATA = [
  {
    aliases: ["The Daughter of the Dusk"],
    allegiances: [],
    books: ["https://www.anapioficeandfire.com/api/books/5"],
    born: "",
    culture: "Braavosi",
    died: "",
    father: "",
    gender: "Female",
    mother: "",
    name: "",
    playedBy: [""],
    povBooks: [],
    spouse: "",
    titles: [""],
    tvSeries: [""],
    url: "https://www.anapioficeandfire.com/api/characters/1",
  },
  {
    aliases: ["Hodor"],
    allegiances: ["https://www.anapioficeandfire.com/api/houses/362"],
    books: [
      "https://www.anapioficeandfire.com/api/books/1",
      "https://www.anapioficeandfire.com/api/books/2",
      "https://www.anapioficeandfire.com/api/books/3",
      "https://www.anapioficeandfire.com/api/books/5",
      "https://www.anapioficeandfire.com/api/books/8",
    ],
    born: "",
    culture: "",
    died: "",
    father: "",
    gender: "Male",
    mother: "",
    name: "Walder",
    playedBy: ["Kristian Nairn"],
    povBooks: [],
    spouse: "",
    titles: [""],
    tvSeries: ["Season 1", "Season 2", "Season 3", "Season 4", "Season 6"],
    url: "https://www.anapioficeandfire.com/api/characters/2",
  },
  {
    aliases: ["Lamprey"],
    allegiances: ["https://www.anapioficeandfire.com/api/houses/15"],
    books: ["https://www.anapioficeandfire.com/api/books/3"],
    born: "",
    culture: "",
    died: "",
    father: "",
    gender: "Male",
    mother: "",
    name: "",
    playedBy: [""],
    povBooks: [],
    spouse: "",
    titles: [""],
    tvSeries: [""],
    url: "https://www.anapioficeandfire.com/api/characters/3",
  },
  {
    aliases: ["The Merling Queen"],
    allegiances: [],
    books: [
      "https://www.anapioficeandfire.com/api/books/5",
      "https://www.anapioficeandfire.com/api/books/8",
    ],
    born: "",
    culture: "Braavosi",
    died: "",
    father: "",
    gender: "Female",
    mother: "",
    name: "",
    playedBy: [""],
    povBooks: [],
    spouse: "",
    titles: [""],
    tvSeries: [""],
    url: "https://www.anapioficeandfire.com/api/characters/4",
  },
  {
    aliases: ["Old Crackbones"],
    allegiances: [],
    books: ["https://www.anapioficeandfire.com/api/books/5"],
    born: "",
    culture: "",
    died: "",
    father: "",
    gender: "Male",
    mother: "",
    name: "",
    playedBy: [""],
    povBooks: [],
    spouse: "",
    titles: [""],
    tvSeries: [""],
    url: "https://www.anapioficeandfire.com/api/characters/5",
  },
  {
    aliases: ["The Poetess"],
    allegiances: [],
    books: ["https://www.anapioficeandfire.com/api/books/5"],
    born: "",
    culture: "Braavosi",
    died: "",
    father: "",
    gender: "Female",
    mother: "",
    name: "",
    playedBy: [""],
    povBooks: [],
    spouse: "",
    titles: [""],
    tvSeries: [""],
    url: "https://www.anapioficeandfire.com/api/characters/6",
  },
  {
    aliases: ["Porridge"],
    allegiances: ["https://www.anapioficeandfire.com/api/houses/15"],
    books: ["https://www.anapioficeandfire.com/api/books/3"],
    born: "",
    culture: "",
    died: "",
    father: "",
    gender: "Female",
    mother: "",
    name: "",
    playedBy: [""],
    povBooks: [],
    spouse: "",
    titles: [""],
    tvSeries: [""],
    url: "https://www.anapioficeandfire.com/api/characters/7",
  },
  {
    aliases: ["Quickfinger"],
    allegiances: ["https://www.anapioficeandfire.com/api/houses/23"],
    books: ["https://www.anapioficeandfire.com/api/books/6"],
    born: "",
    culture: "",
    died: "",
    father: "",
    gender: "Male",
    mother: "",
    name: "",
    playedBy: [""],
    povBooks: [],
    spouse: "",
    titles: [""],
    tvSeries: [""],
    url: "https://www.anapioficeandfire.com/api/characters/8",
  },
  {
    aliases: ["the Sailor's Wife"],
    allegiances: [],
    books: ["https://www.anapioficeandfire.com/api/books/5"],
    born: "",
    culture: "",
    died: "",
    father: "",
    gender: "Female",
    mother: "",
    name: "",
    playedBy: [""],
    povBooks: [],
    spouse: "",
    titles: [""],
    tvSeries: ["2"],
    url: "https://www.anapioficeandfire.com/api/characters/9",
  },
  {
    aliases: ["The Veiled Lady"],
    allegiances: [],
    books: ["https://www.anapioficeandfire.com/api/books/5"],
    born: "",
    culture: "Braavosi",
    died: "",
    father: "",
    gender: "Female",
    mother: "",
    name: "",
    playedBy: [""],
    povBooks: [],
    spouse: "",
    titles: [""],
    tvSeries: ["1"],
    url: "https://www.anapioficeandfire.com/api/characters/10",
  },
];
